"""
Module 4: LLM + Trust Engine
File: response_formatter.py
Purpose: Format raw LLM outputs and trust evaluation metrics into Markdown, JSON, and Frontend response objects.
"""

from typing import Dict, Any, List
from pathlib import Path
try:
    from utils import llm_logger
except (ImportError, AttributeError):
    import importlib.util
    _ut_path = Path(__file__).resolve().parent / "utils.py"
    _spec = importlib.util.spec_from_file_location("mod4_utils", _ut_path)
    _mod = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_mod)
    llm_logger = getattr(_mod, "llm_logger")


class ResponseFormatter:
    """Converts raw LLM text and trust data into standardized response objects."""

    def format_frontend_response(
        self,
        query: str,
        answer: str,
        trust_evaluation: Dict[str, Any],
        citations: List[Dict[str, Any]],
        ranked_sources: List[Dict[str, Any]],
        conflict_info: Dict[str, Any],
        processing_time_ms: float = 0.0
    ) -> Dict[str, Any]:
        """Format response into complete object for API and Frontend consumption.

        Args:
            query (str): User query string.
            answer (str): Text answer generated by LLM.
            trust_evaluation (Dict[str, Any]): Trust score evaluation dictionary.
            citations (List[Dict[str, Any]]): Source citations.
            ranked_sources (List[Dict[str, Any]]): Ranked source chunks.
            conflict_info (Dict[str, Any]): Conflict resolution details.
            processing_time_ms (float): End-to-end response time in milliseconds.

        Returns:
            Dict[str, Any]: Standardized JSON-serializable API/Frontend response object.
        """
        markdown_body = self.format_markdown_response(
            answer=answer,
            trust_evaluation=trust_evaluation,
            citations=citations,
            conflict_info=conflict_info
        )

        formatted_response = {
            "query": query,
            "answer": answer,
            "markdown_response": markdown_body,
            "trust_score": trust_evaluation.get("trust_score", 0.0),
            "trust_percentage": trust_evaluation.get("trust_percentage", 0.0),
            "confidence_level": trust_evaluation.get("confidence_level", "Unknown"),
            "trust_breakdown": trust_evaluation.get("metric_breakdown", {}),
            "citations": citations,
            "sources": [
                {
                    "rank": s.get("rank", idx + 1),
                    "file_name": s.get("metadata", {}).get("source_file", "unknown"),
                    "chunk_id": s.get("id", ""),
                    "score": s.get("hybrid_score", 0.0),
                    "preview": s.get("document", "")[:150] + "..." if len(s.get("document", "")) > 150 else s.get("document", "")
                }
                for idx, s in enumerate(ranked_sources)
            ],
            "conflict_resolution": conflict_info,
            "processing_time_ms": round(processing_time_ms, 2)
        }

        llm_logger.info(f"Formatted frontend response object for query '{query}'.")
        return formatted_response

    def format_markdown_response(
        self,
        answer: str,
        trust_evaluation: Dict[str, Any],
        citations: List[Dict[str, Any]],
        conflict_info: Dict[str, Any]
    ) -> str:
        """Format answer and trust breakdown into standard GitHub Markdown string.

        Args:
            answer (str): Answer string.
            trust_evaluation (Dict[str, Any]): Trust score breakdown.
            citations (List[Dict[str, Any]]): Citations list.
            conflict_info (Dict[str, Any]): Conflict resolution details.

        Returns:
            str: Markdown formatted response.
        """
        score_pct = trust_evaluation.get("trust_percentage", 0.0)
        confidence = trust_evaluation.get("confidence_level", "Medium Confidence")
        breakdown = trust_evaluation.get("metric_breakdown", {})

        md_lines = [
            answer,
            "\n---",
            f"### 🛡️ Trust & Provenance Assessment",
            f"- **Overall Trust Score:** `{score_pct}%` ({confidence})",
            f"- **Semantic Similarity:** `{breakdown.get('semantic_similarity', 0)}%`",
            f"- **Source Reliability:** `{breakdown.get('source_reliability', 0)}%`",
            f"- **Graph Consistency:** `{breakdown.get('graph_consistency', 0)}%`",
            f"- **Citation Coverage:** `{breakdown.get('citation_coverage', 0)}%`",
            ""
        ]

        if citations:
            md_lines.append("#### 📚 Verified Source References:")
            for cit in citations:
                md_lines.append(f"- {cit.get('formatted_citation', '')}")
            md_lines.append("")

        if conflict_info.get("conflict_detected", False):
            md_lines.append(f"> ⚠️ **Conflict Note:** {conflict_info.get('resolution_notes', '')}")

        return "\n".join(md_lines)


if __name__ == "__main__":
    formatter = ResponseFormatter()
    res = formatter.format_frontend_response(
        query="What is GraphRAG?",
        answer="GraphRAG integrates Knowledge Graphs with Vector Search.",
        trust_evaluation={"trust_score": 0.88, "trust_percentage": 88.0, "confidence_level": "High Confidence", "metric_breakdown": {"semantic_similarity": 90, "source_reliability": 85, "graph_consistency": 85, "citation_coverage": 90}},
        citations=[{"formatted_citation": "[Source 1: GraphRAG.pdf]"}],
        ranked_sources=[{"id": "c1", "hybrid_score": 0.9, "document": "GraphRAG text sample.", "metadata": {"source_file": "GraphRAG.pdf"}}],
        conflict_info={"conflict_detected": False, "resolution_notes": "No conflicts."}
    )
    print("Formatted Response Preview Key:\n", res["trust_percentage"], "%")
